### ISSUE TITLE
S3 endpoint config property should not include the protocol

### ISSUE THREAD

**Issue by facundofc** [canonical/mimir-coordinator-k8s-operator#44]
### Bug Description

When relating the coordinator with something implementing the `s3` interface (`ceph-radosgw` from the `reef/edge` channel in my case), the `endpoint` value on the worker's config wrongly includes the protocol (`http(s)`). The rendered config is:

```yaml
s3:
  access_key_id: __THE_KEY__
  bucket_name: mimir
  endpoint: http://10.18.2.87:80
  region: ''
  secret_access_key: __THE_KEY__
```
 And the mimir service doesn't run, logging this plus a traceback:

```
Endpoint url cannot have fully qualified paths.
initialize s3 client
...
```

Manually modifying the `/etc/mimir/mimir-config.yaml` file to remove `http://` allows Mimir to run.

### To Reproduce

I don't have a _minimum_ reproducer, but this is roughly my setup:

1. Deployed microk8s with ceph as storage backend plus the ceph-radosgw to use as Mimir's object store.

```yaml
machines:
  '0':
  '1':
  '2':
applications:
  microk8s:
    charm: microk8s
    channel: 1.28/stable
    series: jammy
    num_units: 3
    to:
    - '0'
    - '1'
    - '2'
  ceph-mon:
    charm: ceph-mon
    channel: quincy/stable
    num_units: 3
    bindings:
      "": oam-space
    to:
    - '0'
    - '1'
    - '2'
  ceph-osd:
    charm: ceph-osd
    channel: quincy/stable
    num_units: 3
    bindings:
      "": oam-space
    to:
    - '0'
    - '1'
    - '2'
    options:
      osd-devices: /dev/vdb
  ceph-csi:
    charm: ceph-csi
    channel: 1.28/stable
    options:
      provisioner-replicas: 1
      namespace: kube-system
  ceph-radosgw:
     charm: ceph-radosgw
     channel: reef/edge
     to: [lxd:0]
  ntp:
    charm: ntp
    channel: stable
relations:
- - microk8s:juju-info
  - ntp:juju-info
- - ceph-osd:mon
  - ceph-mon:osd
- - ceph-csi:ceph-client
  - ceph-mon:client
- - ceph-csi:kubernetes-info
  - microk8s

2. Create a k8s model using the just deployed microk8s as substrate, call it `cos`.
3. Deployed this bundle to it:

```yaml
bundle: kubernetes
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/edge
    base: ubuntu@20.04/stable
    scale: 1
    storage:
      data: kubernetes,1,2048M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: latest/stable
    base: ubuntu@20.04/stable
    scale: 1
    trust: true
  grafana:
    charm: grafana-k8s
    channel: latest/stable
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 67
      litestream-image: 43
    scale: 1
    storage:
      database: kubernetes,1,2048M
    trust: true
  mimir:
    charm: mimir-coordinator-k8s
    channel: edge
    revision: 6
    resources:
      nginx-image: 2
    scale: 1
    constraints: arch=amd64
    trust: true
  mimir-worker:
    charm: mimir-worker-k8s
    channel: edge
    revision: 4
    resources:
      mimir-image: 2
    scale: 3
    options:
      alertmanager: true
      compactor: true
      distributor: true
      ingester: true
      querier: true
      query-frontend: true
      query-scheduler: true
      ruler: true
      store-gateway: true
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
      recovery-data: kubernetes,1,1024M
    trust: true
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    base: ubuntu@20.04/stable
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - mimir:mimir-cluster
  - mimir-worker:mimir-cluster
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - grafana:grafana-source
  - alertmanager:grafana-source
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - grafana:grafana-source
  - mimir:grafana-source
- - grafana:grafana-dashboard
  - mimir:grafana-dashboards-provider
```
4. Offered the `s3` endpoint from the `ceph-radosgw` and related it with `mimir`.

### Environment

I'm using:

* Juju 3.3.1
* Microk8s 1.28
* Ceph Quincy (except for the object store which is Reef, because it implements the `s3` interface)

### Relevant log output

```shell
Endpoint url cannot have fully qualified paths.
initialize s3 client
github.com/thanos-io/objstore/providers/s3.NewBucketWithConfig
	/root/parts/mimir/build/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:273
github.com/grafana/mimir/pkg/storage/bucket/s3.NewBucketClient
	/root/parts/mimir/build/pkg/storage/bucket/s3/bucket_client.go:27
github.com/grafana/mimir/pkg/storage/bucket.NewClient
	/root/parts/mimir/build/pkg/storage/bucket/client.go:163
github.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats
	/root/parts/mimir/build/pkg/mimir/modules.go:971
github.com/grafana/dskit/modules.(*Manager).initModule
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run
	/root/parts/mimir/build/pkg/mimir/mimir.go:812
main.main
	/root/parts/mimir/build/cmd/mimir/main.go:227
runtime.main
	/snap/go/10489/src/runtime/proc.go:267
runtime.goexit
	/snap/go/10489/src/runtime/asm_amd64.s:1650
create usage-stats bucket client
github.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats
	/root/parts/mimir/build/pkg/mimir/modules.go:973
github.com/grafana/dskit/modules.(*Manager).initModule
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run
	/root/parts/mimir/build/pkg/mimir/mimir.go:812
main.main
	/root/parts/mimir/build/cmd/mimir/main.go:227
runtime.main
	/snap/go/10489/src/runtime/proc.go:267
runtime.goexit
	/snap/go/10489/src/runtime/asm_amd64.s:1650
error initialising module: usage-stats
github.com/grafana/dskit/modules.(*Manager).initModule
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/root/parts/mimir/build/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run
	/root/parts/mimir/build/pkg/mimir/mimir.go:812
main.main
	/root/parts/mimir/build/cmd/mimir/main.go:227
runtime.main
	/snap/go/10489/src/runtime/proc.go:267
runtime.goexit
	/snap/go/10489/src/runtime/asm_amd64.s:1650
```
```


### Additional context

_No response_
