### ISSUE TITLE
Mimir is forwarding the wrong address to grafana agents

### ISSUE THREAD

**Issue by simskij** [canonical/mimir-coordinator-k8s-operator#51]
### Bug Description

When relating over `receive-remote-write`, Mimir is forwarding the wrong address. Rather than providing the ingressed address, it provides the cluster-local dito.

### To Reproduce

```
bundle: kubernetes
applications:
  agent:
    charm: grafana-agent-k8s
    channel: latest/edge
    revision: 67
    resources:
      agent-image: 39
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  alertmanager:
    charm: alertmanager-k8s
    channel: edge
    revision: 107
    base: ubuntu@20.04/stable
    resources:
      alertmanager-image: 88
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: edge
    revision: 33
    base: ubuntu@20.04/stable
    resources:
      catalogue-image: 32
    scale: 1
    options:
      description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
        highly-integrated, \nJuju-based observability suite running on Kubernetes.\n"
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: edge
    revision: 109
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 68
      litestream-image: 43
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  loki:
    charm: loki-k8s
    channel: edge
    revision: 128
    base: ubuntu@20.04/stable
    resources:
      loki-image: 92
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,1024M
      loki-chunks: kubernetes,1,1024M
    trust: true
  mimir:
    charm: mimir-coordinator-k8s
    channel: latest/edge
    revision: 8
    resources:
      nginx-image: 3
    scale: 1
    constraints: arch=amd64
    trust: true
  mimir-worker:
    charm: mimir-worker-k8s
    channel: latest/edge
    revision: 7
    resources:
      mimir-image: 3
    scale: 1
    options:
      all: true
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
      recovery-data: kubernetes,1,1024M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: edge
    revision: 173
    base: ubuntu@20.04/stable
    resources:
      prometheus-image: 141
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  traefik:
    charm: traefik-k8s
    channel: edge
    revision: 177
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 159
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - traefik:ingress
  - mimir:ingress
- - agent:send-remote-write
  - mimir:receive-remote-write
- - agent:metrics-endpoint
  - prometheus:self-metrics-endpoint
- - mimir:mimir-cluster
  - mimir-worker:mimir-cluster
```

### Environment

- juju 3.4.0
- microk8s 1.29.2, rev 6529

### Relevant log output

```shell
2024-04-08T09:09:22.904Z [pebble] GET /v1/notices?timeout=30s 30.000352674s 200
2024-04-08T09:09:37.940Z [agent] ts=2024-04-08T09:09:37.940278491Z caller=dedupe.go:112 agent=prometheus instance=80271c6d5a08ec7a6e6b5e228abfbf1a component=remote level=error remote_name=80271c-c8fd86 url=http://mimir-0.mimir-endpoints.test.svc.cluster.local:8080/api/v1/push msg="non-recoverable error while sending metadata" count=274 err="server returned HTTP status 404 Not Found: <html>"
2024-04-08T09:09:42.441Z [agent] ts=2024-04-08T09:09:42.441917944Z caller=dedupe.go:112 agent=prometheus instance=80271c6d5a08ec7a6e6b5e228abfbf1a component=remote level=error remote_name=80271c-c8fd86 url=http://mimir-0.mimir-endpoints.test.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=165 exemplarCount=0 err="server returned HTTP status 404 Not Found: <html>"
```

**Comment by simskij** [comment]
This could be because of a bug in how mimir uses ingress.

```
  - relation-id: 28
    endpoint: ingress
    related-endpoint: ingress
    application-data: {}
    related-units:
      mimir/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.212/32
          ingress-address: 10.152.183.212
          private-address: 10.152.183.212
```

leading to traefik going blocked.
