### ISSUE TITLE
Mimir is not setting `insecure: true` for the s3 relation when provided a non-ssl url

### ISSUE THREAD

**Issue by simskij** [canonical/mimir-coordinator-k8s-operator#52]
### Bug Description

When relating mimir to a ceph-radosgw not set up to run SSL, mimir wrongly assumes an SSL connection, leading to all connection attempts failing. This can be resolved by setting the config property `common.storage.s3.insecure` to `true` whenever an HTTP endpoint is received.

### LXD Model

```
default-base: ubuntu@22.04/stable
saas:
  mimir:
    url: uk8s:admin/test.mimir
applications:
  ceph-radosgw:
    charm: ceph-radosgw
    channel: latest/edge
    revision: 572
    num_units: 1
    to:
    - "3"
    expose: true
    options:
      port: 80
      ssl_cert: ""
      ssl_key: ""
    constraints: arch=amd64
  dashboard:
    charm: ceph-dashboard
    channel: reef/stable
    revision: 49
  microceph:
    charm: microceph
    channel: reef/candidate
    revision: 32
    num_units: 3
    to:
    - "0"
    - "1"
    - "2"
    constraints: arch=amd64
    storage:
      manual: loop,1024M
      osd-standalone: loop,2048M
machines:
  "0":
    constraints: arch=amd64
  "1":
    constraints: arch=amd64
  "2":
    constraints: arch=amd64
  "3":
    constraints: arch=amd64
relations:
- - ceph-radosgw:mon
  - microceph:radosgw
- - ceph-radosgw:s3
  - mimir:s3
```

### K8s Model
```
bundle: kubernetes
saas:
  remote-d59c7a2d5fea47a5898239fea281cf9c: {}
applications:
  agent:
    charm: grafana-agent-k8s
    channel: latest/edge
    revision: 67
    resources:
      agent-image: 39
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  alertmanager:
    charm: alertmanager-k8s
    channel: edge
    revision: 107
    base: ubuntu@20.04/stable
    resources:
      alertmanager-image: 88
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: edge
    revision: 33
    base: ubuntu@20.04/stable
    resources:
      catalogue-image: 32
    scale: 1
    options:
      description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
        highly-integrated, \nJuju-based observability suite running on Kubernetes.\n"
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: edge
    revision: 109
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 68
      litestream-image: 43
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  loki:
    charm: loki-k8s
    channel: edge
    revision: 128
    base: ubuntu@20.04/stable
    resources:
      loki-image: 92
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,1024M
      loki-chunks: kubernetes,1,1024M
    trust: true
  mimir:
    charm: mimir-coordinator-k8s
    channel: latest/edge
    revision: 8
    resources:
      nginx-image: 3
    scale: 1
    constraints: arch=amd64
    trust: true
  mimir-worker:
    charm: mimir-worker-k8s
    channel: latest/edge
    revision: 7
    resources:
      mimir-image: 3
    scale: 1
    options:
      all: true
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
      recovery-data: kubernetes,1,1024M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: edge
    revision: 173
    base: ubuntu@20.04/stable
    resources:
      prometheus-image: 141
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  traefik:
    charm: traefik-k8s
    channel: edge
    revision: 177
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 159
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - traefik:ingress
  - mimir:ingress
- - agent:send-remote-write
  - mimir:receive-remote-write
- - agent:metrics-endpoint
  - prometheus:self-metrics-endpoint
- - mimir:mimir-cluster
  - mimir-worker:mimir-cluster
- - mimir:s3
  - remote-d59c7a2d5fea47a5898239fea281cf9c:s3
--- # overlay.yaml
applications:
  mimir:
    offers:
      mimir:
        endpoints:
        - s3
        acl:
          admin: admin
```

### Environment

- juju 3.4.0
- microk8s 1.29.2, rev 6529

### Relevant log output

```shell
2024-04-08T09:18:03.337Z [mimir] ts=2024-04-08T09:18:03.261337323Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client; ruler storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client"
2024-04-08T09:18:08.037Z [mimir] ts=2024-04-08T09:18:08.003464826Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client; ruler storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client"
2024-04-08T09:18:12.137Z [mimir] ts=2024-04-08T09:18:12.07522605Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client; ruler storage: unable to successfully send a request to object storage: Get \"https://10.99.252.65:80/mimir/?location=\": http: server gave HTTP response to HTTPS client"
```
